qwen1.5_0.5b:
  prompt_template: "mini_lima/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/home/jiahe/LLMs/lima/model_cache/qwen/Qwen1___5-0___5B"
    # model_name: "/home/jiahe/LLMs/lima/LLaMA-Factory/checkpoints/qwen_sft"
    model_kwargs:
      torch_dtype: "bfloat16"
      trust_remote_code: True
      attn_implementation: "flash_attention_2"
    temperature: 0.7
    do_sample: True
    max_new_tokens: 1024
    top_p: 1.0
  pretty_name: "Qwen1.5-0.5B"